# Generated by Django 4.2.11 on 2025-03-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_no',
            new_name='phoneNo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
